name: Test APX

on:
  push:
    paths:
      - 'apx/**'
  pull_request:
    paths:
      - 'apx/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apx

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: apx/go.mod
          cache-dependency-path: apx/go.sum

      - name: Run tests
        run: go test ./...
